### ISSUE TITLE
backgroundTimeout feels worrisome

### ISSUE THREAD

**Issue by smaug----** [WICG/pending-beacon#31]
(just to capture an issue which was discussed during TPAC meeting)
backgroundTimeout would let background tabs to ping server regularly even if timers and such on the background page were heavily throttled. One could do something like
```
document.onvisibilitychange = function() {
  if (document.visibilityState == "hidden") {
    for (let i = 0; i < 1000; ++i) {
      new PendingGetBeacon(url, { backgroundTimeout: i * 3600 });
    }
  }
}
```
and that would let server side to know the page is still open.

**Comment by fergald** [comment]
To a first approximation, if a page is open then it can send pings and I don't think a user would be surprised to find out that an open page can communicate to the server (users can't tell if a page's event loop has been frozen or not). So it doesn't seem like this is a violation of user expectations.

So, the new information leaking here is that a page has been open _and_ frozen for some time.

If the page was ever unfrozen, this info would be also knowable without this API. If the browser did not implement freezing, the openness would be knowable.

Also, I think a service worker would make this knowable.

Any page doing this is going to send 100s of beacons "simultaneously" if the user closes the page in the near future, so it's unlikely to be common practice. Although browser-side rate limiting would presumably prevent that.

Is there a concrete reason to be concerned?

**Comment by fergald** [comment]
Thanks. That is different to a concrete privacy concern, for example.

I think it's reasonable for implementations to limit the number of beacons coming from frozen/backgrounded pages and delay them until the page is unfrozen. All we should promise is that this better than using keep-alive or sendBeacon, without making any promises about the timing of when beacons will be sent.

**Comment by mingyc** [comment]
Just want to clarify:

1. The current proposed API let browser decide when to send a beacon
   > `backgroundTimeout`: the beacon is not guaranteed to be sent at exactly this many milliseconds after hidden, because the browser has freedom to bundle/batch multiple beacons
2. Thanks for catching the case. I think your example should only trigger background sending "next time" the page is hidden per latest explainer
   > `backgroundTimeout`: ... specifying a timeout in milliseconds whether the timer starts after the page enters the next hidden visibility state.

Although I need to verify whether our implementation follow this behavior.

**Comment by mingyc** [comment]
This is now `activateAfter` field in `fetchLater(url, {activateAfter: X})`. See https://github.com/whatwg/fetch/pull/1647#issuecomment-1770705664 for the naming & behavior discussions.
