### ISSUE TITLE
Timeout IDL types

### ISSUE THREAD

**Issue by domenic** [WICG/pending-beacon#44]
See https://w3ctag.github.io/design-principles/#numeric-types

You should definitely add `[EnforceRange]`, to both the dictionary and the attribute. I understand sometimes there are technical reasons to avoid `unsigned long long` but I doubt they apply in this case...

**Comment by mingyc** [comment]
The timeout option is now `activateAfter` in `fetchLater()` API which is a [DOMHighResTimeStamp](https://w3c.github.io/hr-time/#dom-domhighrestimestamp). See https://whatpr.org/fetch/1647.html#dom-deferredrequestinit-activateafter
