### ISSUE TITLE
Spec, repo, and API names are not consistent

### ISSUE THREAD

**Issue by philipwalton** [WICG/pending-beacon#46]
There are a number of different names used here:

- `unload-beacon` (repo name and spec URL slug)
- `Page Unload Beacon` (spec title)
- `PendingBeacon` (base interface)

I'm assuming these inconsistencies are just due to names change over time. If so, I think it makes sense to standard on a single name across the spec title, URL, and base interface.

My recommendation would be to standardize on "Pending Beacon", so the above would become:

- `https://github.com/WICG/pending-beacon` (repo name)
- `https://wicg.github.io/pending-beacon/` (spec URL slug)
- `Pending Beacon` (spec title)
- `PendingBeacon` (base interface, _unchanged_)

I also think we should make this change before the API goes into Origin Trial later this month. When the API goes into Origin Trial people are going to start writing and talking about it. As it stands now, I'm not sure if anyone will know what to call it, which will probably lead to confusion and multiple different names being used.

cc: @clelland

**Comment by mingyc** [comment]
Thanks for suggestion! I am going to rename the content & the spec. For the repo name, we need @yoavweiss's help.

**Comment by yoavweiss** [comment]
Renamed!
