### ISSUE TITLE
Pending(Get|Post)Beacon vs PendingBeacon("(Get|Post)", ....

### ISSUE THREAD

**Issue by sefeng211** [WICG/pending-beacon#59]
Have we considered to shape the API as `PendingBeacon("Get", ...)` and `PendingBeacon("Post", ...)`? This would match what the `fetch` and `XHR` do. It seems uncommon with the current setup.

**Comment by mingyc** [comment]
cc @fergald 
It is mainly for easier type safety to make the API shape look like this.

**Comment by fergald** [comment]
If we made them the same class then we would have to specify that certain methods (like `setUrl` or `setData`) will raise exceptions when called on the wrong kind. Making them different classes avoids that and for typescript coders, it becomes a compile-time error to call `setUrl` of a POST beacon.

**Comment by mingyc** [comment]
The API is now repurposed as `fetchLater()` which supports both HTTP methods. https://github.com/whatwg/fetch/pull/1647
