### ISSUE TITLE
Fetch confusion

### ISSUE THREAD

**Issue by annevk** [WICG/pending-beacon#63]
> This is written as though Fetch were used as the underlying mechanism. However, since these are sent out-of-band, an implementation might not use the actual web-exposed Fetch API, and may instead use the underlying HTTP primitives directly.

That's not what fetch is. This has to use fetch and part of what this has to do as part of that is explain how policies get enforced.

**Comment by mingyc** [comment]
Addressed in https://github.com/whatwg/fetch/pull/1647
