### ISSUE TITLE
[Fetch-Based API] Limiting the scope of pending requests 

### ISSUE THREAD

**Issue by mingyc** [WICG/pending-beacon#72]
Context: #70 and https://github.com/WICG/pending-beacon/pull/71

Even if moving toward a fetch-based design, this proposal does still not focus on supporting every type of requests as beacons. 

For example, it's non-goal to support most of [HTTP methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods), i.e. being able to defer an `OPTION` or `TRACE` until page destroyed. It aldo does not make sense to allow setting `keepalive: false` for a deferred request.

We should look into fields of [RequestInit](https://fetch.spec.whatwg.org/#requestinit) and decide whether `deferSend` should throw errors on some of their values:

- `keepalive`: must be `true`. `{deferSend: new DeferSend(), keepalive: false}` conflicts with each other.
- `url`: supported.
- `method`: one of `GET` or `POST`.
- `headers`: supported.
- `body`: only supported for `POST`.
- `signal`: supported.
- `credentials`: enforcing `same-origin` to be consistent.
- `cache`: not supported?
- `redirect`: enforcing `follow`?
- `referrer`: enforcing same-origin URL?
- `referrerPolicy`: enforcing `same-origin`?
- `integrity`: not supported?
- `priority`: enforcing `auto`?

As shown above, at least `keepalive: true` and `method` need to be enforced. 

If going with this route, can we also consider the [PendingRequest API](https://docs.google.com/document/d/1QQFFa6fZR4LUiyNe9BJQNK7dAU36zlKmwf5gcBh_n2c/edit#heading=h.xs53e9immw2r) approach that proposes a subclass of `Request` to enforce the above?

**Comment by mingyc** [comment]
@yoavweiss @clelland @annevk Could you please take a look?

**Comment by yoavweiss** [comment]
^^ @noamr

**Comment by noamr** [comment]
See [this comment](https://github.com/WICG/pending-beacon/issues/70#issuecomment-1486404787). I think that it's OK if we define that deferred fetches have to be keepalive. The rest are perhaps not that necessary? We can also mandate GET/POST but I'm not sure that's necessary either.

**Comment by mingyc** [comment]
Do do you prefer to limit the request? Just throwing TypeError?

**Comment by noamr** [comment]
> Do do you prefer to limit the request? Just throwing TypeError?

Yes like keepalives. Remove the responsibility of having to auto flush partial beacons while the doc is alive from fetch. Each origin manages its own partial beacon and if the quota is exceeded it's a network error.

This would meet the requirement of "the minimal additions to fetch to make the use case possible"

**Comment by annevk** [comment]
Hey @mingyc, sorry for not having been part of the earlier discussions, but when you say "non-goal" it would really help if that came with a link. It's not clear to me why we would not allow some or all of these things to be as expressive as `fetch()` is.

**Comment by mingyc** [comment]
It comes from [the motivation](https://github.com/WICG/pending-beacon#problem-and-motivation) for this proposal, that we want to provide an alternative to calling `addEventListener('unload', ()=> navigator.sendBeacon());` for analytic purpose, which actually only support POST with data. Even going with `fetch()`-based approach, we don't think it's a requirement to support all possible types of requests.

**Comment by yoavweiss** [comment]
I think it may make sense to currently limit implemented support to GET and POST, while still enabling future extension for other methods, if that becomes required. For that, we'd need to think of a way for developers to recognize lack of support in the future (e.g. by rejecting the promise with a NotSupportedError DOMException for not-yet-supported methods).

**Comment by annevk** [comment]
I guess I don't really understand why we would limit them?

**Comment by annevk** [comment]
That's a surprising statistic. Would love to see HTTPArchive crawl data as to why that is the case.

To the topic at hand, `navigator.sendBeacon()` is a thin wrapper around fetch and fetch is strictly more capable. I'm still not sure why we'd introduce another networking API that is less capable.

**Comment by mingyc** [comment]
Could you suggest how we should proceed with this (fetch-based) proposal?

**Comment by annevk** [comment]
@noamr has been working on that in #70, no?

**Comment by mingyc** [comment]
`fetchLater()` API [spec](https://whatpr.org/fetch/1647.html#dom-global-fetch-later) nows take the same `RequestInfo` object as `fetch()`, and a `DeferredRequestInit` which extendes `RequestInit`.
