### ISSUE TITLE
[Fetch-Based API] `sendAfterBeingBackgroundedTimeout` and `deferSend`

### ISSUE THREAD

**Issue by mingyc** [WICG/pending-beacon#73]
Context: #70 and #71

```js
class DeferSend {
  constructor(sendAfterBeingBackgroundedTimeout)
}
```

Current proposal is to make `deferSend` a class, and `sendAfterBeingBackgroundedTimeout` its optional field.

1. Should this be a standalone option in [`RequestInit`]? But it is not relevant to other existing fetch options.
2. Should the timeout support sending after `hidden` or `pagehide` (bfcached)? (Previous discussion in #13).
3. Need user input for how desirable for this option.
4. Need better naming suggestion.

**Comment by mingyc** [comment]
@yoavweiss @clelland @philipwalton @annevk Could you please take a look?

**Comment by philipwalton** [comment]
(Adding @tunetheweb to take a look while I'm on leave.)

**Comment by yoavweiss** [comment]
^^ @noamr

**Comment by yoavweiss** [comment]
@mingyc - I think this is quite different from the Controller-based design we discussed. Let's sync about this.

**Comment by mingyc** [comment]
The `SendSignal` controller is tracked in https://github.com/WICG/pending-beacon/issues/75

**Comment by mingyc** [comment]
* `sendAfterBeingBackgroundedTimeout` is now `activateAfter` in `fetchLater()` API. See https://github.com/whatwg/fetch/pull/1647#issuecomment-1770705664
* `deferSend` is now the default behavior of `fetchLater()` API. See `Deferred fetching` https://whatpr.org/fetch/1647.html#deferred-fetching
