### ISSUE TITLE
[Fetch-Based API] `SendSignal`

### ISSUE THREAD

**Issue by mingyc** [WICG/pending-beacon#75]
Context: #70 #71

This is to observe a event to tell if a `deferSend` request is still pending.

To prevent from data races, the underlying implementation should ensure that renderer is authoritative to the request's send state when it's alive. Similar to [this discussion](https://github.com/WICG/pending-beacon/issues/10#issuecomment-1189804245) for PendingBeacon.

**Comment by noamr** [comment]
See [https://github.com/WICG/pending-beacon/issues/70#issuecomment-1486404787]. I wonder if we need sentSignal, given a per-origin quota instead of a global quota for beacons.

**Comment by mingyc** [comment]
noamr@ Could you tell why sentSignal is bound to request quota?

Another reason to have it (or `pending` state) is to tell if the request has been sent if it stays in BFCache for more than `backgroundTimeout`

**Comment by noamr** [comment]
> noamr@ Could you tell why sentSignal is bound to request quota?
> 
> Another reason to have it (or `pending` state) is to tell if the request has been sent if it stays in BFCache for more than `backgroundTimeout`

If the document is in BFCache, how would you receive that promise? When you're restored from BFCache?

**Comment by mingyc** [comment]
It can only be received and triggered after restored from BFCache. But at least users can know that their request has been sent.

**Comment by mingyc** [comment]
`SendSignal` is now the returned `FetchLaterResult.activated` field in `fetchLater()` API. See https://whatpr.org/fetch/1647.html#dom-fetchlaterresult-activated
