### ISSUE TITLE
[Fetch-Based API] Handling Request Size Limit

### ISSUE THREAD

**Issue by mingyc** [WICG/pending-beacon#76]
Context: #70 #71

As setting `deferSend` implies `keepalive` is also true, such request has to share the same size limit budget as a regular keepalive request’s [one][fetch-keepalive-quota]: "for each fetch group, the sum of contentLength and inflightKeepaliveBytes <= 64 KB".

To comply with the limit, there are several options:

1. `fetch()` throws `TypeError` whenever the budget has exceeded. Users will not be able to create new pending requests.
2. The browser forces sending out other existing pending requests, in FIFO order, when the budget has exceeded. For a single request > 64KB, `fetch()` should still throws `TypeError`.
3. Ignore the size limit if [BackgroundFetch] Permission is enabled for the page.

[fetch-keepalive-quota]: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
[BackgroundFetch]: https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API#browser_compatibility

**Comment by mingyc** [comment]
Today's discussion:

* Proposal 1: Per-Origin quota
  * Flush the earliest queued request as soon as we reach the limit.
  * For a single request > request size limit, fail the request?
* Proposal 2: 
  * Fail all requests made after we reach the limit
* Refer to compression API
* Need examples with the new API shape options

cc @noamr

**Comment by yoavweiss** [comment]
One thing to be wary of, and that per-origin quota helps a lot with, is weird dynamics that can be created if the quota is shared between multiple 3P vendors on the page.

**Comment by mingyc** [comment]
See https://whatpr.org/fetch/1647.html#deferred-fetching:


6. Let totalScheduledDeferredBytesForOrigin be 0.

...

9. If totalScheduledDeferredBytesForOrigin is greater than 64 kilobytes, then throw a "[QuotaExceededError](https://webidl.spec.whatwg.org/#quotaexceedederror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

**Comment by mingyc** [comment]
Subsequent discussion in https://github.com/WICG/pending-beacon/issues/87
